# Prosta baza użytkowników na start
[passwords]
admin = "BlackStag2026!"
klient = "SpectraStart"
[email]
user = "m.redzinski@blackstagfx.com" # Konto, do którego przypisany jest alias
password = "knfs qxfm qkzj gqkn"     # Hasło wygenerowane dla konta głównego
alias = "spectra@blackstagfx.com"         # Adres, który zobaczy klient
receiver = "spectra@blackstagfx.com"       # Tu chcesz dostawać powiadomienia